spring:
  application:
    name: My-website-Back-end
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://jairam:jairam@cluster0.skyqx.mongodb.net/website?retryWrites=true&w=majority&appName=Cluster0}
      database: website
      ssl:
        enabled: true

server:
  port: 8081

jwt:
  secret: ${JWT_SECRET:mysupersecretkeymysupersecretkeymysupersecretkey}