spring:
  data:
    mongodb:
      uri: mongodb+srv://jairam:jairam@cluster0.skyqx.mongodb.net/website?retryWrites=true&w=majority&appName=Cluster0

jwt:
  secret: mysupersecretkeymysupersecretkeymysupersecretkey