spring:
  application:
    name: My-website-Back-end
  data:
    mongodb:
      uri: mongodb+srv://jairam:jairam@cluster0.skyqx.mongodb.net/website?retryWrites=true&w=majority&appName=Cluster0
      ssl:
        enabled: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

server:
  port: 8081

jwt:
  secret: mysupersecretkeymysupersecretkeymysupersecretkey

java:
  runtime:
    version: 21